version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx-latest

  certbot:
    build:
      context: .
      dockerfile: Dockerfile.certbot

  flask:
    build: .
    expose:
      - 5000
    depends_on:
      - nginx
    environment:
      - FLASK_ENV=production
    image: flask-latest


volumes:
  certbot-conf:
  certbot-www: