FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf
# Add any other Nginx-related configurations or files

# Install Certbot and the Nginx plugin
RUN apt-get update && \
    apt-get install -y certbot python3-certbot-nginx

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]