name: Deploy Server to AWS

on:
  push:
    branches: ['main', 'hotfix/server-pipelines']
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        run: |
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} | aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

      - name: Build, tag, and push Docker image to Amazon ECR Public
        run: |
          IMAGE_TAG="latest"
          IMAGE_URI="${{ secrets.ECR_URI }}/${{ secrets.ECR_REPO_NAME }}:$IMAGE_TAG"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
      
      - name: Cleanup old images from ECR
        run: |
          aws ecr list-images --repository-name ${{ secrets.ECR_REPOSITORY }} --query 'imageIds[?imageTag!=`latest`]' --output json | jq -r '.[] | .imageDigest' | xargs -I {} aws ecr batch-delete-image --repository-name ${{ secrets.ECR_REPOSITORY }} --image-ids imageDigest={}

      - name: Retrieve and Update ECS Task Definition
        run: |
          # Retrieve the current task definition
          aws ecs describe-task-definition --task-definition deploy-to-ec2 > current-task-def.json
          
          # Update the task definition with the new image
          NEW_IMAGE_URI="${{ secrets.ECR_URI }}/${{ secrets.ECR_REPO_NAME }}:latest"
          jq --arg NEW_IMAGE_URI "$NEW_IMAGE_URI" '.taskDefinition.containerDefinitions[0].image = $NEW_IMAGE_URI' current-task-def.json > modified-task-def.json
          
          # Register the new task definition
          NEW_TASK_DEF=$(aws ecs register-task-definition --cli-input-json file://modified-task-def.json)
          NEW_TASK_DEF_ARN=$(echo $NEW_TASK_DEF | jq -r '.taskDefinition.taskDefinitionArn')
          
          echo "New task definition ARN: $NEW_TASK_DEF_ARN"

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service ${{ secrets.ECS_SERVICE_NAME }} --task-definition ${{ env.NEW_TASK_DEFINITION_ARN }} --force-new-deployment
